org: code4mk
app: demo-app-api-fastapi
service: demo-app-api-fastapi

frameworkVersion: '3'

plugins:
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.11
  region: us-east-1

functions:
  demo_app_fastapi:
    handler: lamda_handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any

